### ISSUE TITLE
tkinterライブラリがないと動かない問題

### ISSUE THREAD

**Issue by masatheultimater** [Kouhei-Takagi/RecallWatcher#1]
素直に`git clone`するとモジュールがロードできないって言われます。
![image](https://github.com/Kouhei-Takagi/RecallWatcher/assets/42201824/be2cd66a-fea7-4e2b-81d6-6899caf6df40)

また自分はUbuntu22.04環境で動作確認したので, tkinterがなくOSにPythonGUI系パッケージ(python3-tk?)をインストールしました。

`BeautifulSoup`や`requests`など標準ライブラリでないモジュールが環境によっては存在しないからです。
Pythonに不慣れな人だと起動できないと思うので(Githubで見に来てできない人もあまりいないと思いますが)こちらからこのライブラリが必要だよと指示を出す必要があります。
以下どちらか対応が必要かと思います。

- `reqirements.txt`等に必要ライブラリを記載
- `README.md`に必要ライブラリをインストールしてもらうように記載する

**Comment by Kouhei-Takagi** [comment]
@masatheultimater 
Mergeしました。ありがとうございました。
