### ISSUE TITLE
ネイティブアプリ以外のインターフェース追加で更にウォッチしやすくなる??

### ISSUE THREAD

**Issue by masatheultimater** [Kouhei-Takagi/RecallWatcher#3]
これはtkinterを試す意図が少なからずあったのかと思います。
tkinterのみならず, WebアプリやiOSアプリなどで見れるようになると更に見れる機器が増えて面白いかなと思いました!

**Comment by Kouhei-Takagi** [comment]
@masatheultimater 
悩みどころです。Webアプリは良いと思いました。
ただiOSアプリは、スクレイピングに不向きなため、微妙です。
デスクトップアプリ and Webアプリは、良いかなと思います。

**Comment by masatheultimater** [comment]
@Kouhei-Takagi 
なるほど。
iOSであればUIとAPIへのリクエストのみiPhoneにもたせて
スクレイピング処理とその結果送信はAPIサーバにまかせてみるといいかもしれんすね!
デスクトップアプリもPC見てる人ならいいね!
多分超リアルタイムにリコールがあったか知りたいわけではない人が多い気がするからPCからでも良さそう。
```mermaid
flowchart LR
id1(iphone)-- HTTPリクエスト -->id2(Python?APIサーバー)
id2 -- なんらかのレスポンス --> id1
```
