### ISSUE TITLE
監視結果を時系列・業種別データとして保存して分析すると面白い??

### ISSUE THREAD

**Issue by masatheultimater** [Kouhei-Takagi/RecallWatcher#4]
どんな会社の
どんな業種が
どんなタイミングで
リコールあったのか分析してみるの面白そうと思いました!
この情報のみでなく
その時期にあった社会情勢の情報もあると更に面白い分析できるかも。

自分もリコールがあった会社のものはウォッチしてみたいと思っていたので興味深い。

**Comment by Kouhei-Takagi** [comment]
@masatheultimater 
ナイス助言です。
リコール情報の分析は需要がありそうです。
課題として取り組む予定です。
